import {
  UserAccount,
  ElectionPosition,
  Referendum,
  ValidatorNode,
  ThreatAlert,
  AuditLogEntry,
  BackupSnapshot,
} from '../types';
import { generateBlindVoterToken, sha256Sync } from './crypto';

export const INITIAL_VALIDATOR_NODES: ValidatorNode[] = [
  {
    id: 'node-cs-1',
    name: 'CS Dept Validator Node #1',
    host: 'cs-validator-01.stanford.edu',
    role: 'Primary Consensus Miner',
    status: 'ONLINE',
    latencyMs: 14,
    blocksValidated: 42,
    publicKey: '0x8F9C3...D1A4',
    location: 'Gates Building, Server Room 2B',
  },
  {
    id: 'node-su-2',
    name: 'Student Union Governance Node #2',
    host: 'stu-union-ledger.campus.edu',
    role: 'Electoral Board Witness',
    status: 'ONLINE',
    latencyMs: 18,
    blocksValidated: 40,
    publicKey: '0x4E2B1...7C99',
    location: 'Tressider Memorial Union, Fl 3',
  },
  {
    id: 'node-dean-3',
    name: 'Dean of Student Affairs Integrity Node #3',
    role: 'Audit & Compliance Verifier',
    host: 'dean-integrity.admin.edu',
    status: 'ONLINE',
    latencyMs: 22,
    blocksValidated: 41,
    publicKey: '0x9A77F...3E00',
    location: 'Old Union Administrative Wing',
  },
  {
    id: 'node-lib-4',
    name: 'University Library Digital Vault Node #4',
    host: 'lib-archive.vault.edu',
    role: 'Immutable Storage Archiver',
    status: 'ONLINE',
    latencyMs: 16,
    blocksValidated: 39,
    publicKey: '0x1C65D...88F2',
    location: 'Green Library Special Collections',
  },
];

export const INITIAL_POSITIONS: ElectionPosition[] = [
  {
    id: 'pos-pres',
    title: 'Student Body President',
    description: 'Leads the Associated Students Council, manages the $3.8M student activities budget, and represents the student body in university board meetings.',
    maxSelections: 1,
    candidates: [
      {
        id: 'cand-maya',
        name: 'Maya Chen',
        positionId: 'pos-pres',
        department: 'Engineering & Computer Science',
        classStanding: 'Junior',
        gpa: 3.91,
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
        slogan: 'Transparency, Tech Innovation & 24/7 Academic Support',
        bio: 'Maya is a CS & Symbolic Systems junior, current Student Senate Academic Chair, and developer of the campus course evaluation portal.',
        manifestoPoints: [
          'Expand 24/7 study access across engineering and library facilities with free evening shuttle service.',
          'Implement an open-source student budget dashboard to eliminate hidden fee allocations.',
          'Negotiate university-wide subsidized health insurance for undergraduate and graduate researchers.',
          'Launch a student mental health rapid-response endowment fund.',
        ],
        endorsements: ['Women in Computer Science (WiCS)', 'Campus Green Coalition', 'Graduate Student Council'],
        votesCount: 384,
      },
      {
        id: 'cand-marcus',
        name: 'Marcus Vance',
        positionId: 'pos-pres',
        department: 'Business & Economics',
        classStanding: 'Senior',
        gpa: 3.86,
        avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=300&auto=format&fit=crop&q=80',
        slogan: 'Affordable Campus Life, Career Hubs & Transparent Housing',
        bio: 'Economics senior, Varsity athlete, and former Resident Assistant passionate about student economic empowerment and dining reform.',
        manifestoPoints: [
          'Cap campus meal plan inflation and expand halal, kosher, and vegan dining options.',
          'Establish a $150,000 emergency grant fund for students facing unexpected tuition or medical hardships.',
          'Partner with top tech, finance, and nonprofit firms to bring direct on-campus recruiting days.',
          'Freeze student activity fee hikes for the upcoming academic cycle.',
        ],
        endorsements: ['Undergraduate Business Association', 'Varsity Athlete Council', 'First-Gen Student Alliance'],
        votesCount: 342,
      },
      {
        id: 'cand-elena',
        name: 'Elena Rostova',
        positionId: 'pos-pres',
        department: 'Law & Policy',
        classStanding: 'Senior',
        gpa: 3.95,
        avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300&auto=format&fit=crop&q=80',
        slogan: 'Inclusion, Climate Action & Accessible Student Rights',
        bio: 'Public Policy senior, mock trial captain, and active advocate for campus disability access and environmental divestment.',
        manifestoPoints: [
          'Achieve 100% renewable campus power by 2028 and eliminate single-use plastics from student union.',
          'Audit every campus building for universal ADA wheelchair and neurodivergent accessibility.',
          'Establish a free legal counseling clinic for students dealing with off-campus landlord disputes.',
          'Revamp campus sexual health education and consent awareness workshops.',
        ],
        endorsements: ['Campus Disability Action League', 'Environmental Law Society', 'International Student Guild'],
        votesCount: 298,
      },
    ],
  },
  {
    id: 'pos-vp',
    title: 'Vice President of Student Affairs',
    description: 'Oversees 200+ registered student organizations, campus wellness initiatives, and major campus traditions.',
    maxSelections: 1,
    candidates: [
      {
        id: 'cand-devon',
        name: 'Devon Patel',
        positionId: 'pos-vp',
        department: 'Health & Medicine',
        classStanding: 'Junior',
        gpa: 3.88,
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
        slogan: 'Proactive Mental Health & Vibrant Club Life',
        bio: 'Bioengineering & Pre-Med student, EMS campus volunteer, and coordinator for the Annual Campus Spring Carnival.',
        manifestoPoints: [
          'Same-day counseling check-in slots at Vaden Health Center.',
          'Streamline student club funding approvals to under 48 hours.',
          'Host bi-weekly campus food truck nights and outdoor cinema socials.',
        ],
        endorsements: ['Peer Health Advocates', 'Pre-Med Student Association'],
        votesCount: 462,
      },
      {
        id: 'cand-sophia',
        name: 'Sophia Kim',
        positionId: 'pos-vp',
        department: 'Arts & Humanities',
        classStanding: 'Junior',
        gpa: 3.82,
        avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=300&auto=format&fit=crop&q=80',
        slogan: 'Empowering Student Voices & Creative Arts Funding',
        bio: 'Art Practice and Communications major, curator of the Stanford Arts Showcase, and community muralist.',
        manifestoPoints: [
          'Double the grant pool for creative arts, music ensembles, and independent student films.',
          'Open dedicated 24/7 rehearsal and podcasting studio spaces in residential dorms.',
          'Create a campus-wide cultural festival honoring international heritage months.',
        ],
        endorsements: ['Student Arts Collective', 'Asian American Student Association'],
        votesCount: 395,
      },
    ],
  },
  {
    id: 'pos-treasurer',
    title: 'Treasurer & Financial Controller',
    description: 'Allocates grants, manages treasury investments, and ensures compliance with campus fiscal regulations.',
    maxSelections: 1,
    candidates: [
      {
        id: 'cand-zack',
        name: 'Zachary Thornton',
        positionId: 'pos-treasurer',
        department: 'Business & Economics',
        classStanding: 'Senior',
        gpa: 3.93,
        avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
        slogan: 'Zero Waste Spending & Maximum Club Funding',
        bio: 'Finance and Management Science major with experience auditing student group allocations and investment portfolios.',
        manifestoPoints: [
          '100% real-time digital expense tracking visible to all student taxpayers.',
          'Eliminate redundant administrative budget overhead to redirect $120k back to student clubs.',
          'Institute zero-interest micro-loans for student-led campus startups and social ventures.',
        ],
        endorsements: ['Stanford Finance', 'Campus Entrepreneurial Hub'],
        votesCount: 512,
      },
      {
        id: 'cand-ananya',
        name: 'Ananya Sharma',
        positionId: 'pos-treasurer',
        department: 'Natural Sciences',
        classStanding: 'Junior',
        gpa: 3.89,
        avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80',
        slogan: 'Ethical Investments & Equitable Resource Distribution',
        bio: 'Applied Math & Statistics major, passionate about data-driven budget modeling and financial accessibility.',
        manifestoPoints: [
          'Shift 20% of treasury reserves into community-focused, ESG-certified green micro-funds.',
          'Provide standardized financial training workshops for new student organization treasurers.',
          'Automatic grant matching for community service and humanitarian student initiatives.',
        ],
        endorsements: ['Women in Math', 'Social Impact Scholars'],
        votesCount: 420,
      },
    ],
  },
];

export const INITIAL_REFERENDUMS: Referendum[] = [
  {
    id: 'ref-transit',
    code: 'PROP-2026-A',
    title: '24/7 Green Campus Transit & Night-Owl Shuttle Expansion',
    description: 'Shall the student body approve a $12 per quarter dedicated fee to expand clean-energy electric bus routes to run 24 hours a day between campus, transit hubs, and nearby residential housing?',
    fullText: 'The proposed measure guarantees zero-emission electric buses operating at 10-minute intervals between 10:00 PM and 6:00 AM, equipped with student ID security tap readers and real-time GPS tracking in the Stanford Mobile app.',
    options: [
      { id: 'opt-transit-yes', label: 'YES (Approve $12 Fee & 24/7 Transit)', votesCount: 782 },
      { id: 'opt-transit-no', label: 'NO (Reject Measure)', votesCount: 198 },
      { id: 'opt-transit-abstain', label: 'ABSTAIN', votesCount: 44 },
    ],
  },
  {
    id: 'ref-health',
    code: 'PROP-2026-B',
    title: 'Campus Mental Wellness & Tele-Health 24/7 Support Initiative',
    description: 'Shall the Associated Students charter a permanent Mental Wellness Committee with dedicated professional tele-health licenses provided at zero out-of-pocket cost to all enrolled students?',
    fullText: 'Provides 24/7 on-demand psychiatric and counseling access via secure mobile portal, reducing wait times from an average of 14 days down to same-day urgent sessions.',
    options: [
      { id: 'opt-health-yes', label: 'YES (Establish Permanent Charter & 24/7 Tele-Health)', votesCount: 896 },
      { id: 'opt-health-no', label: 'NO (Maintain Current Status Quo)', votesCount: 88 },
      { id: 'opt-health-abstain', label: 'ABSTAIN', votesCount: 40 },
    ],
  },
];

export const DEMO_USERS: UserAccount[] = [
  {
    id: 'usr-student-alex',
    studentId: 'STU-2026-9814',
    fullName: 'Alex Morgan',
    email: 'alex.morgan@stanford.edu',
    role: 'VOTER',
    department: 'Engineering & Computer Science',
    classStanding: 'Junior',
    hasVoted: false,
    hasBiometricRegistered: true,
    twoFactorEnabled: true,
    twoFactorSecret: 'STANFORD_VOTER_MFA_SECRET_789',
    encryptedVoterToken: generateBlindVoterToken('STU-2026-9814', 'alex.morgan@stanford.edu'),
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    ipAddress: '171.64.12.84',
  },
  {
    id: 'usr-official-sarah',
    studentId: 'OFFICIAL-2026-004',
    fullName: 'Dr. Sarah Jenkins',
    email: 'elections-chair@stanford.edu',
    role: 'ELECTION_OFFICIAL',
    department: 'Law & Policy',
    classStanding: 'Senior',
    hasVoted: true,
    hasBiometricRegistered: true,
    twoFactorEnabled: true,
    twoFactorSecret: 'OFFICIAL_MFA_SECRET_456',
    encryptedVoterToken: generateBlindVoterToken('OFFICIAL-2026-004', 'elections-chair@stanford.edu'),
    avatarUrl: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80',
    ipAddress: '171.64.1.10',
  },
  {
    id: 'usr-auditor-liam',
    studentId: 'AUDITOR-2026-001',
    fullName: 'Liam O’Connor',
    email: 'cyber-auditor@stanford.edu',
    role: 'AUDITOR',
    department: 'Engineering & Computer Science',
    classStanding: 'Graduate',
    hasVoted: true,
    hasBiometricRegistered: true,
    twoFactorEnabled: true,
    twoFactorSecret: 'AUDITOR_MFA_SECRET_123',
    encryptedVoterToken: generateBlindVoterToken('AUDITOR-2026-001', 'cyber-auditor@stanford.edu'),
    avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
    ipAddress: '171.64.99.201',
  },
];

export const INITIAL_THREAT_ALERTS: ThreatAlert[] = [
  {
    id: 'threat-101',
    timestamp: Date.now() - 1000 * 60 * 25,
    type: 'BRUTE_FORCE',
    title: 'Rapid Failed Biometric/2FA Handshake Detected',
    description: '14 rapid token verification failures from foreign subnet 185.220.101.5 within 45 seconds targeting voter ID batch STU-2026-88XX.',
    severity: 'HIGH',
    sourceIp: '185.220.101.5 (Tor Exit Node)',
    status: 'RESOLVED',
    mitigation: 'Automated IP rate limiter engaged; IP quarantined for 24 hours; affected account tokens re-keyed.',
  },
  {
    id: 'threat-102',
    timestamp: Date.now() - 1000 * 60 * 12,
    type: 'IMPOSSIBLE_TRAVEL',
    title: 'Geo-Velocity Anomaly in Voter Session Token',
    description: 'Voter session token authenticated from Stanford Campus WiFi (171.64.12.84) and 4 minutes later re-attempted from Frankfurt, Germany (84.115.22.1).',
    severity: 'MEDIUM',
    sourceIp: '84.115.22.1',
    affectedAccount: 'STU-2026-4421',
    status: 'ACTIVE',
    mitigation: 'Step-up mandatory 2FA biometric re-challenge enforced. Foreign IP blocked.',
  },
  {
    id: 'threat-103',
    timestamp: Date.now() - 1000 * 60 * 4,
    type: 'DOUBLE_VOTE_ATTEMPT',
    title: 'Replay Attack Prevented: Duplicate Blind Token Re-Submission',
    description: 'Incoming ballot transaction attempted using blind token hash 0x3f8e... that was already recorded in Block #3. Zero-Knowledge double-spend check rejected ballot.',
    severity: 'HIGH',
    sourceIp: '171.64.88.42',
    status: 'INVESTIGATING',
    mitigation: 'Transaction dropped at consensus memory pool; alert dispatched to Election Security Officers.',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'log-001',
    timestamp: Date.now() - 1000 * 60 * 60 * 3,
    category: 'BLOCKCHAIN',
    actor: 'Node #1 (CS Dept)',
    actorRole: 'AUDITOR',
    action: 'Genesis Block Minted',
    details: 'Genesis block initialized with cryptographic difficulty target 0x0000FFFF. 4 validator consensus established.',
    ipAddress: '171.64.10.1',
    status: 'SUCCESS',
    tamperProofHash: sha256Sync('GENESIS_BLOCK_INITIALIZED_2026'),
  },
  {
    id: 'log-002',
    timestamp: Date.now() - 1000 * 60 * 60 * 2,
    category: 'ADMIN',
    actor: 'Dr. Sarah Jenkins',
    actorRole: 'ELECTION_OFFICIAL',
    action: 'Election Parameters Certified',
    details: 'Official certified candidate slate and 2 campus referendums for the 2026 Spring General Election.',
    ipAddress: '171.64.1.10',
    status: 'SUCCESS',
    tamperProofHash: sha256Sync('ADMIN_CERTIFICATION_SARAH_2026'),
  },
  {
    id: 'log-003',
    timestamp: Date.now() - 1000 * 60 * 45,
    category: 'SECURITY',
    actor: 'Automated Threat Guard',
    actorRole: 'AUDITOR',
    action: 'Brute Force Quarantine Applied',
    details: 'Flagged 14 malicious token injection attempts from 185.220.101.5. Subnet quarantined.',
    ipAddress: '185.220.101.5',
    status: 'WARNING',
    tamperProofHash: sha256Sync('THREAT_MITIGATED_TOR_185'),
  },
  {
    id: 'log-004',
    timestamp: Date.now() - 1000 * 60 * 18,
    category: 'BALLOT',
    actor: 'Anonymous Voter (ZK-Verified)',
    actorRole: 'VOTER',
    action: 'Encrypted Ballot Cast & Signed',
    details: 'Ballot verified via Biometric FaceID + 2FA TOTP. Broadcast to 4 validator nodes and queued for Block #4.',
    ipAddress: '171.64.14.92',
    status: 'SUCCESS',
    tamperProofHash: sha256Sync('VOTE_ANONYMOUS_CAST_RECEIPT_004'),
  },
  {
    id: 'log-005',
    timestamp: Date.now() - 1000 * 60 * 5,
    category: 'BLOCKCHAIN',
    actor: 'Node #2 (Student Union)',
    actorRole: 'AUDITOR',
    action: 'Block #3 Validated & Merkle Root Sealed',
    details: 'Block #3 mined with 12 encrypted ballot transactions. Merkle root: 0x9b4c... consensus 4/4 unanimous.',
    ipAddress: '171.64.20.2',
    status: 'SUCCESS',
    tamperProofHash: sha256Sync('BLOCK_3_SEALED_MERKLE_ROOT'),
  },
];

export const INITIAL_BACKUPS: BackupSnapshot[] = [
  {
    id: 'snap-20260817-0400',
    timestamp: Date.now() - 1000 * 60 * 60,
    version: 'v4.2.1-genesis-sealed',
    totalBlocks: 3,
    totalVotes: 1024,
    checksum: 'sha256:8f4c2e...b901',
    sizeKb: 348.6,
    autoGenerated: true,
  },
  {
    id: 'snap-20260817-0300',
    timestamp: Date.now() - 1000 * 60 * 120,
    version: 'v4.2.0-pre-poll-open',
    totalBlocks: 2,
    totalVotes: 650,
    checksum: 'sha256:3a1b9e...77c2',
    sizeKb: 215.2,
    autoGenerated: true,
  },
];
