export type UserRole = 'VOTER' | 'ELECTION_OFFICIAL' | 'AUDITOR';

export type ElectionStatus = 'UPCOMING' | 'ACTIVE' | 'PAUSED' | 'FINALIZED';

export type Department = 
  | 'Engineering & Computer Science'
  | 'Business & Economics'
  | 'Arts & Humanities'
  | 'Natural Sciences'
  | 'Health & Medicine'
  | 'Law & Policy';

export type ClassStanding = 'Freshman' | 'Sophomore' | 'Junior' | 'Senior' | 'Graduate';

export interface UserAccount {
  id: string;
  studentId: string;
  fullName: string;
  email: string;
  role: UserRole;
  department: Department;
  classStanding: ClassStanding;
  hasVoted: boolean;
  hasBiometricRegistered: boolean;
  twoFactorEnabled: boolean;
  twoFactorSecret: string;
  encryptedVoterToken: string;
  avatarUrl?: string;
  ipAddress: string;
}

export interface Candidate {
  id: string;
  name: string;
  positionId: string;
  department: Department;
  classStanding: ClassStanding;
  gpa: number;
  avatarUrl: string;
  slogan: string;
  bio: string;
  manifestoPoints: string[];
  endorsements: string[];
  votesCount: number;
}

export interface ElectionPosition {
  id: string;
  title: string;
  description: string;
  maxSelections: number;
  candidates: Candidate[];
}

export interface ReferendumOption {
  id: string;
  label: string;
  votesCount: number;
}

export interface Referendum {
  id: string;
  title: string;
  code: string;
  description: string;
  fullText: string;
  options: ReferendumOption[];
}

export interface BallotVoteChoice {
  positionId: string;
  candidateId: string;
  candidateName: string;
}

export interface BallotReferendumChoice {
  referendumId: string;
  optionId: string;
  optionLabel: string;
}

export interface EncryptedBallot {
  ballotId: string;
  voterTokenHash: string; // Zero-knowledge hashed to preserve voter anonymity
  encryptedPayload: string;
  votes: BallotVoteChoice[];
  referendums: BallotReferendumChoice[];
  timestamp: number;
  signature: string;
  department: Department;
  classStanding: ClassStanding;
}

export interface BlockchainTransaction {
  id: string;
  type: 'VOTE_CAST' | 'CANDIDATE_REGISTERED' | 'ELECTION_STATUS_CHANGE' | 'NODE_VALIDATION' | 'SYSTEM_CONFIG';
  ballotReceiptHash: string;
  voterTokenHash: string;
  encryptedData: string;
  metadata: {
    department: Department;
    classStanding: ClassStanding;
    selectionsSummary: string[];
  };
  timestamp: number;
  validatorSignature: string;
}

export interface BlockchainBlock {
  index: number;
  timestamp: number;
  transactions: BlockchainTransaction[];
  previousHash: string;
  hash: string;
  nonce: number;
  merkleRoot: string;
  validatorNode: string;
  isValid: boolean;
}

export interface ValidatorNode {
  id: string;
  name: string;
  host: string;
  role: string;
  status: 'ONLINE' | 'SYNCING' | 'OFFLINE';
  latencyMs: number;
  blocksValidated: number;
  publicKey: string;
  location: string;
}

export type ThreatSeverity = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

export interface ThreatAlert {
  id: string;
  timestamp: number;
  type: 'BRUTE_FORCE' | 'IMPOSSIBLE_TRAVEL' | 'DOUBLE_VOTE_ATTEMPT' | 'BLOCK_TAMPER' | 'UNAUTHORIZED_CONFIG' | 'ROGUE_TOKEN';
  title: string;
  description: string;
  severity: ThreatSeverity;
  sourceIp: string;
  affectedAccount?: string;
  status: 'RESOLVED' | 'ACTIVE' | 'INVESTIGATING';
  mitigation: string;
}

export type AuditLogCategory = 'AUTH' | 'BALLOT' | 'ADMIN' | 'BLOCKCHAIN' | 'SECURITY';

export interface AuditLogEntry {
  id: string;
  timestamp: number;
  category: AuditLogCategory;
  actor: string;
  actorRole: UserRole;
  action: string;
  details: string;
  ipAddress: string;
  status: 'SUCCESS' | 'WARNING' | 'FAILURE';
  tamperProofHash: string;
}

export interface BackupSnapshot {
  id: string;
  timestamp: number;
  version: string;
  totalBlocks: number;
  totalVotes: number;
  checksum: string;
  sizeKb: number;
  autoGenerated: boolean;
}

export interface AccessibilitySettings {
  highContrast: boolean;
  dyslexiaFont: boolean;
  fontSize: 'normal' | 'large' | 'extra-large';
  soundEnabled: boolean;
  screenReaderAnnouncements: boolean;
}
